"""initial_schema

Revision ID: 9a56f921735c
Revises: 
Create Date: 2026-05-06 17:27:19.746355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a56f921735c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_bolao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_bloqueio_palpites_especiais', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pontos_campeao', sa.Integer(), nullable=False),
    sa.Column('pontos_melhor_jogador', sa.Integer(), nullable=False),
    sa.Column('pontos_artilheiro', sa.Integer(), nullable=False),
    sa.Column('pontos_melhor_goleiro', sa.Integer(), nullable=False),
    sa.Column('pontos_placar_exato', sa.Integer(), nullable=False),
    sa.Column('pontos_resultado_correto', sa.Integer(), nullable=False),
    sa.Column('pontos_classificado_mata_mata', sa.Integer(), nullable=False),
    sa.Column('pontos_marcador_brasil', sa.Integer(), nullable=False),
    sa.Column('pontos_marcador_brasil_com_quantidade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=8), nullable=False),
    sa.Column('bandeira_url', sa.String(length=2048), nullable=False),
    sa.Column('grupo', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('funcao', sa.String(length=255), nullable=True),
    sa.Column('imagem_perfil', sa.String(length=2048), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=32), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('primeiro_login', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('jogos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fase', sa.String(length=128), nullable=False),
    sa.Column('grupo', sa.String(length=16), nullable=True),
    sa.Column('tipo_fase', sa.String(length=32), nullable=False),
    sa.Column('pais_casa_id', sa.Integer(), nullable=False),
    sa.Column('pais_fora_id', sa.Integer(), nullable=False),
    sa.Column('data_jogo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('placar_casa', sa.Integer(), nullable=True),
    sa.Column('placar_fora', sa.Integer(), nullable=True),
    sa.Column('teve_prorrogacao', sa.Boolean(), nullable=False),
    sa.Column('foi_para_penaltis', sa.Boolean(), nullable=False),
    sa.Column('penaltis_casa', sa.Integer(), nullable=True),
    sa.Column('penaltis_fora', sa.Integer(), nullable=True),
    sa.Column('classificado_id', sa.Integer(), nullable=True),
    sa.Column('finalizado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['classificado_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['pais_casa_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['pais_fora_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palpites_especiais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('campeao_id', sa.Integer(), nullable=True),
    sa.Column('melhor_jogador', sa.String(length=255), nullable=True),
    sa.Column('artilheiro', sa.String(length=255), nullable=True),
    sa.Column('melhor_goleiro', sa.String(length=255), nullable=True),
    sa.Column('pontuacao_campeao', sa.Integer(), nullable=False),
    sa.Column('pontuacao_melhor_jogador', sa.Integer(), nullable=False),
    sa.Column('pontuacao_artilheiro', sa.Integer(), nullable=False),
    sa.Column('pontuacao_melhor_goleiro', sa.Integer(), nullable=False),
    sa.Column('pontuacao_total', sa.Integer(), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['campeao_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', name='uq_palpite_especial_usuario')
    )
    op.create_index(op.f('ix_palpites_especiais_usuario_id'), 'palpites_especiais', ['usuario_id'], unique=False)
    op.create_table('resultados_especiais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campeao_id', sa.Integer(), nullable=True),
    sa.Column('melhor_jogador', sa.String(length=255), nullable=True),
    sa.Column('artilheiro', sa.String(length=255), nullable=True),
    sa.Column('melhor_goleiro', sa.String(length=255), nullable=True),
    sa.Column('finalizado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['campeao_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcadores_brasil_resultado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=False),
    sa.Column('nome_jogador', sa.String(length=255), nullable=False),
    sa.Column('quantidade_gols', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcadores_brasil_resultado_jogo_id'), 'marcadores_brasil_resultado', ['jogo_id'], unique=False)
    op.create_table('palpites_jogos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jogo_id', sa.Integer(), nullable=False),
    sa.Column('palpite_casa', sa.Integer(), nullable=True),
    sa.Column('palpite_fora', sa.Integer(), nullable=True),
    sa.Column('palpite_classificado_id', sa.Integer(), nullable=True),
    sa.Column('pontuacao_placar', sa.Integer(), nullable=False),
    sa.Column('pontuacao_resultado', sa.Integer(), nullable=False),
    sa.Column('pontuacao_classificado', sa.Integer(), nullable=False),
    sa.Column('pontuacao_marcadores_brasil', sa.Integer(), nullable=False),
    sa.Column('pontuacao_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ),
    sa.ForeignKeyConstraint(['palpite_classificado_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'jogo_id', name='uq_palpite_usuario_jogo')
    )
    op.create_index(op.f('ix_palpites_jogos_jogo_id'), 'palpites_jogos', ['jogo_id'], unique=False)
    op.create_index(op.f('ix_palpites_jogos_usuario_id'), 'palpites_jogos', ['usuario_id'], unique=False)
    op.create_table('marcadores_brasil_palpite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('palpite_jogo_id', sa.Integer(), nullable=False),
    sa.Column('nome_jogador', sa.String(length=255), nullable=False),
    sa.Column('quantidade_gols', sa.Integer(), nullable=False),
    sa.Column('pontuacao', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['palpite_jogo_id'], ['palpites_jogos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcadores_brasil_palpite_palpite_jogo_id'), 'marcadores_brasil_palpite', ['palpite_jogo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marcadores_brasil_palpite_palpite_jogo_id'), table_name='marcadores_brasil_palpite')
    op.drop_table('marcadores_brasil_palpite')
    op.drop_index(op.f('ix_palpites_jogos_usuario_id'), table_name='palpites_jogos')
    op.drop_index(op.f('ix_palpites_jogos_jogo_id'), table_name='palpites_jogos')
    op.drop_table('palpites_jogos')
    op.drop_index(op.f('ix_marcadores_brasil_resultado_jogo_id'), table_name='marcadores_brasil_resultado')
    op.drop_table('marcadores_brasil_resultado')
    op.drop_table('resultados_especiais')
    op.drop_index(op.f('ix_palpites_especiais_usuario_id'), table_name='palpites_especiais')
    op.drop_table('palpites_especiais')
    op.drop_table('jogos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('paises')
    op.drop_table('configuracoes_bolao')
    # ### end Alembic commands ###
